services:
    fos_user.doctrine_registry:
        alias: doctrine

    shout.counter:
        class: Jam\CoreBundle\Services\ShoutCounter
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]
            - [setTokenStorage, ["@security.token_storage"]]
            - [setShout]

    search.musicians:
        class: Jam\CoreBundle\Services\SearchMusicians
        calls:
            - [setElasticCompatibilityFinder, ["@fos_elastica.finder.searches.compatibility"]]
            - [setGenreFinder, ["@fos_elastica.finder.searches.genres"]]
            - [setInstrumentFinder, ["@fos_elastica.finder.searches.instruments"]]
            - [setElasticUsersFinder, ["@fos_elastica.finder.searches.user"]]
            - [setTokenStorage, ["@security.token_storage"]]
            - [setTracker, ["@happyr.google.analytics.tracker"]]

    search.subscriber.cron:
        class: Jam\CoreBundle\Services\SearchSubscriberCron
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]
            - [setTwig, ["@templating"]]
            - [setMailer, ["@mailer"]]
            - [setLogger, ["@logger"]]
            - [checkMailParams, ["%mailer_user%", "%mailer_password%"]]
            - [setMusiciansSearch, ["@search.musicians"]]

    compatibility.calculator:
            class: Jam\CoreBundle\Services\CompatibilityCalculator
            calls:
                - [setEntityManager, ["@doctrine.orm.entity_manager"]]
                - [setTokenStorage, ["@security.token_storage"]]
                - [setElasticaUsersFinder, ["@fos_elastica.finder.searches.user"]]
                - [setElasticaCompatibilityIndex, ["@fos_elastica.index.searches.compatibility"]]
            tags:
                -  { name: kernel.event_listener, event: security.interactive_login, method: calculate }
                -  { name: kernel.event_listener, event: fos_user.profile.edit.success, method: calculate }
                -  { name: kernel.event_listener, event: fos_user.registration.confirmed, method: calculate }

    jam.types:
        class: Jam\CoreBundle\Services\JamTypes
        arguments: ["@translator"]

    jam.statuses:
        class: Jam\CoreBundle\Services\JamStatuses
        arguments: ["@translator"]

    jam.stages:
        class: Jam\CoreBundle\Services\JamStages
        arguments: ["@translator"]

    app.twig_extension:
        class: Jam\CoreBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
        calls:
            - [setJamTypes, ["@jam.types"]]
            - [setJamStages, ["@jam.stages"]]
            - [setJamStatuses, ["@jam.statuses"]]