services:

    shout.counter:
        class: Jam\CoreBundle\Services\ShoutCounter
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]
            - [setTokenStorage, ["@security.token_storage"]]
            - [setShout]

    search.subscriber.cron:
        class: Jam\CoreBundle\Services\SearchSubscriberCron
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]
            - [setElasticUserFinder, ["@fos_elastica.finder.searches.user"]]
            - [setTwig, ["@templating"]]
            - [setMailer, ["@mailer"]]
            - [setLogger, ["@logger"]]
            - [checkMailParams, [%mailer_user%, %mailer_password%]]

    compatibility.calculator:
            class: Jam\CoreBundle\Services\CompatibilityCalculator
            calls:
                - [setEntityManager, ["@doctrine.orm.entity_manager"]]
                - [setTokenStorage, ["@security.token_storage"]]
                - [setElasticaUsersFinder, ["@fos_elastica.finder.searches.user"]]
                - [setElasticaCompatibilityIndex, ["@fos_elastica.index.searches.compatibility"]]
            tags:
                -  { name: kernel.event_listener, event: security.interactive_login, method: calculate }