imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: fos_elastica.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:
        enabled: true
        api: 2.4
        enable_annotations: true
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  snc_redis.session.handler
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        node_server: %node_server%
        soundcloud_app_id: %soundcloud_app_id%

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        ["JamWebBundle", "JamUserBundle", "FOSUserBundle"]
    node: %node_bin_path%/node
    filters:
        cssrewrite: ~
        less:
            node_paths: [%node_modules_path%/node_modules]
            apply_to: "\.less$"
            preserve_comments: false

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Jam\UserBundle\Entity\User
    registration:
            form:
                type: jam_user_registration
    profile:
            form:
                type: jam_user_profile

stof_doctrine_extensions:
    default_locale: en
    orm:
        default:
            tree: true
            sluggable: true
            translatable: true
            timestampable: true
            softdeleteable: true
            blameable: true

braincrafted_bootstrap:
    output_dir:
    assets_dir:
    jquery_path:
    less_filter: none # "less", "lessphp", "sass" or "none"
    fonts_dir:
    auto_configure:
        assetic: false
        twig: true
        knp_menu: false
        knp_paginator: false
    customize:
        variables_file: ~
        bootstrap_output: %kernel.root_dir%/Resources/less/bootstrap.less
        bootstrap_template: BraincraftedBootstrapBundle:Bootstrap:bootstrap.less.twig

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        my_thumb:
            quality: 75
            filters:
                thumbnail: { size: [50, 50], mode: outbound }
        medium_thumb:
            quality: 75
            filters:
                thumbnail: { size: [200, 140], mode: outbound }
                upscale: { min: [200, 140] }
                crop: { start: [0, 0], size: [200, 140] }
        my_medium:
            quality: 75
            filters:
                relative_resize: { scale: 0.5 }
        my_medium_1:
            quality: 75
            filters:
                thumbnail: { size: [140, 140], mode: outbound }
        my_medium_2:
            quality: 75
            filters:
                thumbnail: { size: [280, 280], mode: outbound }
        my_medium_3:
            quality: 75
            filters:
                thumbnail: { size: [280, 140], mode: outbound }
        my_medium_4:
            quality: 75
            filters:
                thumbnail: { size: [140, 280], mode: outbound }
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://%redis_server%
        cache:
            type: predis
            alias: cache
            dsn: redis://%redis_server%
            logging: true
        session:
            type: predis
            alias: session
            dsn: redis://%redis_server%
#    doctrine:
#        metadata_cache:
#            client: cache
#            entity_manager: default          # the name of your entity_manager connection
#            document_manager: default        # the name of your document_manager connection
#        result_cache:
#            client: cache
#            entity_manager: [default, read]  # you may specify multiple entity_managers
#        query_cache:
#            client: cache
#            entity_manager: default
    session:
        client: session

hwi_oauth:
    #this is my custom user provider, created from FOSUBUserProvider - will manage the
    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
    #and also, the connecting part (get the token and the user_id)
    connect:
        account_connector: my_user_provider
    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_name: main
    fosub:
        username_iterations: 30
        properties:
            # these properties will be used/redefined later in the custom FOSUBUserProvider service.
            facebook: facebook_id
            soundcloud: soundcloud_id
    resource_owners:
        facebook:
            type:                facebook
            client_id:           "%facebook_app_id%"
            client_secret:       "%facebook_app_secret%"
            scope:         "email"
            infos_url:     "https://graph.facebook.com/me?fields=name,email,gender,picture.type(normal)"
            paths:
                email:          email
                profilepicture: picture.data.url
            user_response_class: Jam\UserBundle\Security\Core\User\Response\FacebookResponse
        soundcloud:
            type:                soundcloud
            client_id:           "%soundcloud_app_id%"
            client_secret:       "%soundcloud_app_secret%"
            user_response_class: Jam\UserBundle\Security\Core\User\Response\SoundcloudResponse
    # here you will add one (or more) configurations for resource owners