imports:
    - { resource: config.yml }

doctrine:
    orm:
        metadata_cache_driver: redis
        result_cache_driver: redis
        query_cache_driver: redis

snc_redis:
    doctrine:
        metadata_cache:
            client: cache
            entity_manager: default          # the name of your entity_manager connection
            document_manager: default        # the name of your document_manager connection
        result_cache:
            client: cache
            entity_manager: [default, read]  # you may specify multiple entity_managers
        query_cache:
            client: cache
            entity_manager: default
        second_level_cache:
            client: cache
            entity_manager: default

monolog:
    handlers:
        mail:
            type:         fingers_crossed
            action_level: critical
            handler:      buffered
        buffered:
            type:    buffer
            handler: swift
        swift:
            type:       swift_mailer
            from_email: noreply@jamifind.com
            to_email:   stanic.slobodan88@gmail.com
            subject:    Jamifind: An Error Occurred!
            level:      debug
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  rotating_file
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            max_files: 20
        console:
            type:  console