fos_elastica:
    clients:
        default: { host: %elastic_host%, port: %elastic_port% }
    indexes:
        searches:
            client: default
            index_name: app_%kernel.environment%
            types:
                user:
                    mappings:
                        username: ~
                        firstName: ~
                        lastName: ~
                        pin: { type: geo_point }
                        genres:
                            type: "object"
                            properties:
                                genre.id: ~
                                genre.category.id: ~
                        instruments:
                            type: "object"
                            properties:
                                instrument.id:
                        artists:
                            type: "object"
                            properties:
                                id: { boost: 1.6 }
                        commitment: { boost: 0.3 }
                        age: { boost: 0.2 }
                        isTeacher:
                            type: "boolean"
                        isJammer:
                            type: "boolean"
                        isVisitor:
                            type: "boolean"
                    persistence:
                        driver: orm
                        model: Jam\UserBundle\Entity\User
                        provider: ~
                        finder: ~
                        elastica_to_model_transformer:
                            ignore_missing: true
                shout:
                    mappings:
                        creator:
                            type: "object"
                            properties:
                                pin: { type: geo_point }
                        createdAt: { type: date }
                    persistence:
                        driver: orm
                        model: Jam\CoreBundle\Entity\Shout
                        provider: ~
                        listener: ~
                        finder: ~
                        elastica_to_model_transformer:
                            ignore_missing: true
                genres:
                    mappings:
                        id: ~
                        category.id: ~
                    persistence:
                        driver: orm
                        model: Jam\CoreBundle\Entity\Genre
                        provider: ~
                        listener: ~
                        finder: ~
                        elastica_to_model_transformer:
                            ignore_missing: true
                instruments:
                    mappings:
                        id: ~
                        category.id: ~
                    persistence:
                        driver: orm
                        model: Jam\CoreBundle\Entity\Instrument
                        provider: ~
                        listener: ~
                        finder: ~
                        elastica_to_model_transformer:
                            ignore_missing: true