fos_elastica:
    clients:
        default: { host: %elastic_host%, port: %elastic_port% }
    indexes:
        searches:
            client: default
            types:
                user:
                    mappings:
                        username: ~
                        pin: { type: geo_point }
                    persistence:
                        driver: orm
                        model: Jam\UserBundle\Entity\User
                        provider: ~
                        listener:
                        finder: ~
