fos_elastica:
    clients:
        default: { host: %elastic_host%, port: %elastic_port% }
    indexes:
        searches:
            client: default
            index_name: app_%kernel.environment%
            types:
                user:
                    mappings:
                        username: ~
                        firstName: ~
                        lastName: ~
                        email: ~
                        createdAt: { type: date }
                        pin: { type: geo_point }
                        profileFulfilment:
                            type: "keyword"
                        gender:
                            type: "keyword"
                        location:
                            type: "object"
                            properties:
                                administrative_area_level_3:
                                    type: keyword
                        genres:
                            type: "object"
                            properties:
                                genre.id: ~
                                genre.name:
                                    type: keyword
                                genre.category.id: ~
                        instruments:
                            type: "object"
                            properties:
                                instrument.id: ~
                                instrument.name:
                                    type: keyword
                        artists:
                            type: "object"
                            properties:
                                id: { boost: 1.6, type: "keyword" }
                                name:
                                    type: keyword
                        gear:
                            type: "object"
                            properties:
                                name:
                                    type: keyword
                        commitment: { boost: 0.3, type: "keyword" }
                        age: { boost: 0.2, type: "keyword" }
                        isTeacher:
                            type: "boolean"
                        isJammer:
                            type: "boolean"
                        isVisitor:
                            type: "boolean"
                    persistence:
                        driver: orm
                        model: Jam\UserBundle\Entity\User
                        provider: ~
                        finder: ~
                        elastica_to_model_transformer:
                            ignore_missing: true
                service:
                    mappings:
                        pin: { type: geo_point }
                    persistence:
                        driver: orm
                        model: Jam\CoreBundle\Entity\Service
                        provider: ~
                        finder: ~
                        elastica_to_model_transformer:
                            ignore_missing: true
                shout:
                    mappings:
                        creator:
                            type: "object"
                            properties:
                                pin: { type: geo_point }
                        createdAt: { type: date }
                    persistence:
                        driver: orm
                        model: Jam\CoreBundle\Entity\Shout
                        provider: ~
                        listener: ~
                        finder: ~
                        elastica_to_model_transformer:
                            ignore_missing: true
                genres:
                    mappings:
                        id: ~
                        category.id: ~
                    persistence:
                        driver: orm
                        model: Jam\CoreBundle\Entity\Genre
                        provider: ~
                        listener: ~
                        finder: ~
                        elastica_to_model_transformer:
                            ignore_missing: true
                instruments:
                    mappings:
                        id: ~
                        category.id: ~
                    persistence:
                        driver: orm
                        model: Jam\CoreBundle\Entity\Instrument
                        provider: ~
                        listener: ~
                        finder: ~
                        elastica_to_model_transformer:
                            ignore_missing: true