fos_elastica:
    clients:
        default: { host: %elastic_host%, port: %elastic_port% }
    indexes:
        searches:
            client: default
            types:
                user:
                    mappings:
                        username: ~
                        firstName: ~
                        lastName: ~
                        pin: { type: geo_point }
                        genres:
                            type: "object"
                            properties:
                                genre.id: ~
                        instruments:
                            type: "object"
                            properties:
                                instrument.id:
                        isTeacher:
                            type: "boolean"
                    persistence:
                        driver: orm
                        model: Jam\UserBundle\Entity\User
                        provider: ~
                        listener:
                        finder: ~
                        elastica_to_model_transformer:
                            ignore_missing: true

                shout:
                    mappings:
                        creator:
                            type: "object"
                            properties:
                                pin: { type: geo_point }
                        createdAt: { type: date }
                    persistence:
                        driver: orm
                        model: Jam\CoreBundle\Entity\Shout
                        provider: ~
                        listener:
                        finder: ~
                        elastica_to_model_transformer:
                            ignore_missing: true