_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml

jam_user:
    resource: "@JamUserBundle/Controller/"
    type:     annotation
    prefix:   /

jam_web:
    resource: "@JamWebBundle/Controller/"
    type:     annotation
    prefix:   /

jam_admin:
    resource: "@JamWebBundle/Controller/Admin/"
    type:     annotation
    prefix:   /admin

JMSTranslationBundle_ui:
    resource: "@JMSTranslationBundle/Controller/"
    type:     annotation
    prefix:   /_trans