jam_user:
    resource: "@JamUserBundle/Controller/"
    type:     annotation
    prefix:   /

jam_web:
    resource: "@JamWebBundle/Controller/"
    type:     annotation
    prefix:   /

jam_core:
    resource: "@JamCoreBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

facebook_login:
    pattern: /login/check-facebook

jam_facebook_login:
    pattern: /connect/facebook

soundcloud_login:
    pattern: /login/check-soundcloud

jam_soundcloud_login:
    pattern: /connect/soundcloud

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"