<?php

namespace Jam\CoreBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\FixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Jam\CoreBundle\Entity\Brand;

class LoadBrandsEffectsData implements FixtureInterface
{
    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $brands = array(
"3Leaf Audio"
,"3Xfx"
,"4ms Pedals"
,"65 Amp"
,"A/DA"
,"Ace Tone"
,"Acoustic Imaginearing"
,"Addrock"
,"Aguilar"
,"akai"
,"Akai"
,"Amdek"
,"AMPedals"
,"Ampeg"
,"AMT Electronics"
,"Analogman"
,"Antelope Effects"
,"Aphek"
,"Aphex"
,"Aramat Effects"
,"Arbiter Electronics"
,"Arger"
,"Aria"
,"ArielFX"
,"Arion"
,"Art"
,"Artec"
,"Arteffect"
,"Ashdown"
,"Asonix"
,"Audible Disease"
,"Auxiliary Workshop"
,"AXL"
,"AYA"
,"Bad Cat Amps"
,"Baja Tech Custom"
,"Barber Electronics"
,"Bardel Pedals"
,"Barge Concepts"
,"Bartolini"
,"BBE Sound"
,"Behringer"
,"Bennett Music Labs"
,"Bespeco"
,"Big John"
,"Big Lloyde"
,"Bixonic"
,"Biyang"
,"BJFE"
,"Black Cat"
,"Blackout Effectors"
,"Blackstar Amplification"
,"Blackstone Appliances"
,"BMF Effects"
,"Boomerang Musical Products"
,"Boomstick Audio"
,"Boss"
,"BSM"
,"Budda"
,"BugBrand"
,"Burford Electronics"
,"Burns London"
,"Burriss"
,"BYOC"
,"C Tech"
,"Carl Martin"
,"Catalinbread"
,"Cat's-Eye Custom Analog Effects"
,"Cause & Effect Pedals"
,"Celmo"
,"CheeseBlocks Effects"
,"Chicago Iron"
,"Chunk Systems"
,"Circuit Bent Instruments"
,"Class A Electronics"
,"CMATMODS"
,"Copilot FX"
,"Cornell"
,"Creation Audio Labs"
,"Creepy Fingers Effects"
,"Crowther"
,"Crowther Audio"
,"Cusack Music"
,"D*A*M"
,"Dallas Music"
,"Dallas-Arbiter"
,"Damage Control"
,"Dan Armstrong Effects"
,"Danelectro"
,"Danneburg Electronics"
,"Daphon"
,"DDyna Music"
,"Death by Audio"
,"DeltaLab"
,"Demeter Amplification"
,"Devi ever"
,"DHA"
,"Diamond Guitar Pedals"
,"Diaz"
,"Dice Works"
,"Digitech"
,"Dino's Guitars"
,"Dinosaural"
,"Dirk Hendrik"
,"Dirty Boy"
,"Divided by Thirteen"
,"DLS Effects"
,"DNA Analogic"
,"DOD"
,"Dr. Scientist Sounds"
,"Dredge-Tone"
,"Dunlop"
,"Durham Electronics"
,"Dwarfcraft Devices"
,"DvK Technologies"
,"Dytone"
,"Earthbound Audio"
,"EarthQuaker Devices"
,"Ebow"
,"EBS"
,"Eden Analog"
,"Effectrode"
,"Electric Toad Engineering"
,"Electro Harmonix"
,"ElectroniX"
,"Emma"
,"Empress Effects"
,"Engl"
,"Eowave"
,"EPB-USA"
,"Epicenter Audio"
,"Ernie Ball"
,"Erotic FX Pedals"
,"Euthymia Electronics"
,"Eventide"
,"Exar Electronix"
,"Experimentalists Anonymous"
,"Fairfield Circuitry"
,"Farfisa"
,"FEA Labs"
,"Fender"
,"Flynn Amps"
,"Foxrox Electronics"
,"Foxx"
,"Franklin Pro Pedals"
,"Frantone"
,"Freakshow"
,"Frostwave"
,"Fulltone"
,"Fuzzhugger"
,"Fuzzrocious Pedals"
,"G2D"
,"Gaspedals"
,"GeekMacDaddy"
,"General Guitar Gadgets"
,"George Dennis"
,"Gig-fx"
,"Greedtone"
,"Greer Amplification"
,"Gretsch"
,"Guild"
,"Guyatone"
,"HAO"
,"Hartke"
,"Hartman"
,"Heavy Electronics"
,"Hermida Audio Technology"
,"Himmelstrutz Elektro Art"
,"HipKitty Products"
,"Hiwatt"
,"HomeBrew Electronics"
,"Honey"
,"Hughes and Kettner"
,"Human Gear"
,"Ibanez"
,"Ilitch Electronics"
,"ISP"
,"ISP Technologies"
,"J. Everman Custom Analog Effects"
,"Jacques Stompboxes"
,"Jam Pedals"
,"JangleBox"
,"Jersey Girl"
,"Jetter Gear"
,"jim dunlop"
,"Johnson"
,"JXL"
,"Katanasound"
,"Kay"
,"Keeler Designs"
,"Keeley"
,"King Capitol Punishment"
,"Klon"
,"Korg"
,"KR Musical Products"
,"Krank Amplification"
,"Landmine Pedal Co."
,"    LastGasp Art Laboratories"
,"Lee Jackson"
,"Lehle"
,"Lemon Studio Sound"
,"Lightfoot Labs"
,"Line 6"
,"Lock & Rock"
,"LocoBox"
,"Lovekraft Effects"
,"Lovepedal"
,"Lovetone"
,"LS Effects"
,"Ludwig"
,"Mad Professor"
,"Maestro"
,"Mahoney"
,"Malekko Heavy Industries"
,"Markbass"
,"Marshall"
,"Matchless Amplifiers"
,"Maxon"
,"Mellowtone"
,"Menatone"
,"Mesa/Boogie"
,"Metal Pedals"
,"MG Music"
,"Mi Audio"
,"Mid-Fi Electronics"
,"MJM Guitar FX"
,"ModMax"
,"ModTone"
,"MOEN"
,"Mojo Hand"
,"Molten Voltage"
,"Monolith Fuzz"
,"Monster Effects"
,"Moody Sounds"
,"Moog"
,"Moollon"
,"Moonphaser"
,"Morley"
,"Mosrite"
,"Mountainking Electronics"
,"Musician Sound Design"
,"Musitronics"
,"MXR"
,"MythFX"
,"Nady Systems"
,"Nine Volt Nirvana"
,"Nobels"
,"NOC3 Effects"
,"OceanEFX"
,"Officially Licensed Circuits"
,"OKKO"
,"OM Laboratories"
,"Onerr"
,"OohLaLa Manufacturing"
,"Open Stomp"
,"Option 5"
,"Orange"
,"Outlaw Supply"
,"Owen Electronics"
,"Owen James Originals"
,"Oxfuzz FX"
,"Pax"
,"Pearl"
,"Pedal Tank"
,"PedalDoctor FX"
,"PedalWorX"
,"Penny Pedals"
,"Pete Cornish"
,"Pfeiffer"
,"Pharaoh Amplifiers"
,"Phoenix Custom Electronics"
,"Pignose-Gorilla"
,"Pigtronix"
,"Plum Crazy FX"
,"Plush FX"
,"Prescription Electronics"
,"Pro Co"
,"ProAnalog"
,"proco"
,"ProTone Pedals"
,"Providence"
,"Psionic Audio"
,"Radial Engineering"
,"Railhead Effects"
,"Real McCoy Custom"
,"Red Witch"
,"REDesign"
,"RedZone Effects"
,"Retroman"
,"Retro-Sonic"
,"RGW Electronics"
,"Road Rage Pro-Gear"
,"Robert Keeley Electronics"
,"Robot Factory"
,"Rock and Roll Workshop"
,"Rockett Pedals"
,"Rocktek"
,"Rocktron"
,"Roger Linn Design"
,"Roger Mayer"
,"Rogue"
,"Roland"
,"Ross"
,"Rothwell"
,"RTZ Audio"
,"RWS Effects"
,"Schumann Electronics"
,"Screaming Baby Amplifiers"
,"Seamoon"
,"Seppuku"
,"Seymour Duncan"
,"Shin-ei"
,"SIB"
,"Skreddy Pedals"
,"SLM"
,"Smallsound/Bigsound"
,"Snarling Dogs"
,"Solid Gold Sound Labs"
,"Songworks"
,"Source Audio"
,"SpF"
,"SubDecay"
,"SuperKing Pedals"
,"Superpuma"
,"Sweet Sound Electronics"
,"Swell"
,"Systech"
,"t rex"
,"T. Miranda"
,"T. Rex"
,"Taurus"
,"Taylor"
,"TC Electronic"
,"Tech 21"
,"Teisco"
,"Telenordia"
,"THD"
,"The Squarewave Parade"
,"Thomas Organ"
,"Throbak Electronics"
,"Toadworks"
,"Toe-Jam Pedals"
,"Tonality Effects"
,"Tone Freak Effects"
,"Tone in Progress"
,"ToneBias"
,"tonebone"
,"ToneCandy"
,"ToneCzar"
,"Tonerider"
,"Tonesonics"
,"TopHat"
,"Torres Engineering"
,"Tortuga Effects"
,"Trace Elliott"
,"Trachouse Pedals"
,"Trailer Trash"
,"T-Rex"
,"Tronographic"
,"Tycobrahe"
,"Tym"
,"Ulbrick Sound"
,"Uncle Ernie's Effects"
,"Univox"
,"Urso Music"
,"Wampler Pedals"
,"Van Amps"
,"Washburn"
,"Wattson Classic Electronics"
,"Way Huge Electronics"
,"VHT"
,"Will Sledge FX"
,"Wilson Effects"
,"Vintage Technology"
,"Vintage Tone Project"
,"VintageFX"
,"Visual Sound"
,"WMD Instrument Effects"
,"Voodoo Lab"
,"Vox"
,"Wren and Cuff Creations"
,"Xotic"
,"Yamaha"
,"Zoom"
,"Zvex"
        );

        foreach ($brands as $b) {
            $brand = new Brand();
            $brand->setName(trim($b));
            $brand->setParent('effects');
            $manager->persist($brand);
        }

        $manager->flush();
    }
}