<?php

namespace Jam\CoreBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\FixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Jam\CoreBundle\Entity\Brand;

class LoadBrandsBassData implements FixtureInterface
{
    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $brands = array(
"A Basses"
,"Adler Custom Guitars"
,"Alembic"
,"Alleva Coppolo"
,"Alter Ego"
,"Ambush Custom Basses"
,"Andre van der End"
,"Andrews Guitar"
,"Antonis Bass"
,"Aquilina Basses"
,"Aria Guitars"
,"Aristides Instruments"
,"Aristone"
,"Artinger Guitars"
,"Aspe Guitars"
,"Atelier Z"
,"Auerswald Instruments"
,"AYS Bass & Guitars"
,"Azola Basses"
,"B. Hefner Company"
,"B.C. Rich"
,"Bacchus"
,"Barker Bass"
,"BassLab"
,"Batson Guitars"
,"Beck Guitarworks"
,"Bee Basses"
,"Belman Guitars"
,"Benavente Guitars"
,"Benedict Guitars"
,"Bennett Guitars"
,"Birdsong Guitars"
,"Boerjes"
,"Bolin Guitars"
,"Born To Rock"
,"Breedlove Guitars"
,"Brian Moore Custom Guitars"
,"Brubaker Guitars"
,"Bruno Traverso Guitars"
,"Buckdancer's Choice"
,"Bunker Guitars"
,"Burns Guitars"
,"C. F. Martin & Company"
,"California Guitars"
,"CallowHill"
,"Carl Thompson Guitars"
,"Carvin.com"
,"CB Basses"
,"Celinder"
,"Chandler Guitars"
,"Christof Kost Bässe"
,"Citron Guitars"
,"Clement Bass"
,"Clevinger Bass"
,"Collier Basses"
,"Colmenares Bass Guitars"
,"Conklin Guitars"
,"Cort Guitars"
,"Crook Custom Guitars"
,"D.M. Guitars"
,"Daisy Rock Guitars"
,"Dammann Basses"
,"Danelectro"
,"Dave Maize Acoustic Guitars"
,"David King Bass Guitars"
,"De Lacugo Guitars"
,"Dean Guitars"
,"Dean Markley Strings"
,"Devon Guitars"
,"Diego Pons"
,"Dillon Guitars"
,"Dingwall Designer Guitars"
,"Dipinto Guitars"
,"DNG Guitares"
,"DP Custom Guitars"
,"Eastwood Guitars"
,"Eccleshall"
,"Egholm Bass Guitars"
,"Ellio Martina Guitars"
,"Elrick Bass Guitars"
,"ESP Guitars"
,"Eugen Guitars"
,"F Bass"
,"Fano"
,"Fender"
,"Fernandes Guitars"
,"Fichter E-Kontrabässe"
,"Fina Guitar"
,"Fleabass"
,"Fleishman Instruments"
,"Fodera"
,"Framus"
,"Fret-King"
,"Fury Guitar"
,"G&L Musical Instruments"
,"G. Edward Lutherie"
,"G. Gould Music"
,"Gadow Guitars"
,"GB Guitars"
,"Gecko Guitars"
,"Genta"
,"Gibson Guitar Corporation"
,"Giffin Guitars"
,"Global Guitars"
,"GMP Guitars"
,"GMR"
,"Godin Guitars"
,"Godlyke"
,"GR Basses"
,"Greco"
,"Gretsch Drums and Guitars"
,"Grosh Guitars"
,"Guild Guitars"
,"Guitar Factory"
,"Gus Guitars"
,"Hagstrom Bass Guitars"
,"HAL's FUNK-Bass"
,"Hamer Guitars"
,"Hanewinckel Guitars"
,"Hartke"
,"Harvey Citron Enterprises"
,"Haze Guitars"
,"Heins Guitars"
,"Hembrook"
,"Heritage Guitar Inc."
,"Hill Instruments"
,"Hoag Light Beam Guitars"
,"Hofner"
,"Hohner"
,"Hot Wire Bass"
,"Human Base Instruments"
,"Ibanez"
,"Indie Guitars"
,"Infeld"
,"Italia Guitars"
,"J.Backlund Design Guitars"
,"Jackson/Charvel Guitar Company"
,"James Basses"
,"James Trussart Custom Guitars"
,"Jay Turser Guitars"
,"Jaydee Custom Bass Guitars"
,"Jeff Mallia Lutherie"
,"Jerry Jones Guitars"
,"Jerzy Drozd Basses"
,"Jim Reed Guitars"
,"JJ Helms"
,"Joe's Guitars"
,"John Birch Guitars"
,"Johnson's Extremely Strange M.I"
,"JPBasses"
,"JT Hargreaves Acoustic B&G"
,"Kamil Greben"
,"Kania"
,"Karl Hoyt"
,"Kasim Sulton Bass"
,"Kawai Bass Guitars"
,"Ken Bebensee Instruments"
,"Ken Rose"
,"Ken Smith Basses"
,"Kinal"
,"Klein Electric Guitars"
,"Knooren Handcrafted Instruments"
,"Koll Guitars"
,"Kot Basses"
,"Kramer Guitars"
,"Kubicki"
,"Kydd Basses"
,"L.A. Kidwell Musical Instrument"
,"LA Guitar Factory"
,"Lado Guitars"
,"Lakland"
,"Landing Guitars"
,"Landscape"
,"Laurus Basses"
,"Le Fay"
,"Lecompte Electric Bass"
,"Leduc Guitars & Basses"
,"Legg Guitars"
,"Levin Guitars"
,"Lieber Guitars"
,"LightWave Systems"
,"Linc Luthier Instruments"
,"Line 6"
,"Little Guitar Works"
,"Lodestone Guitars"
,"Longbow Guitars"
,"Lovell Custom Guitars"
,"Luna Guitars"
,"M Basses"
,"Malden Guitars"
,"Manne Guitars"
,"Mari by RediVivus"
,"Marleaux Bass Guitars"
,"Maton"
,"Matt Pulcinella Guitars"
,"Mayones Guitars & Basses"
,"Merchant Bass"
,"Messenger Upright Electric Bass"
,"Michael Dolan Guitars"
,"Michael Kelly Guitars"
,"Michael Tobias Design"
,"Mike Lull Custom Guitars"
,"Miller Guitars & Basses"
,"Mobius Megatar"
,"Modulus Guitars"
,"Mollerup Basses"
,"Monterey Guitars"
,"Moonstone Guitars"
,"Moses Graphite"
,"Music Man"
,"Musicvox Guitars"
,"Mørch Guitars"
,"Nardelli Electric Bass"
,"National Reso-Phonic Guitars"
,"Neubauer Guitars"
,"Neuser Basses"
,"New York Bass Works"
,"Nevborn Guitars"
,"Noguera Bass"
,"Nordstrand Guitars"
,"Novax Guitars"
,"NS Design"
,"Odyssey Guitars"
,"Olivo"
,"Ovation"
,"Overwater Basses"
,"Paul Reed Smith Guitars"
,"Pavel Musical instruments"
,"Peavey"
,"Pedulla"
,"Pensa Custom Guitars"
,"Petillo Guitars"
,"Phantom Guitars"
,"Pirles"
,"Prat Basses"
,"Ray Ramírez Basses"
,"Read Custom Instruments"
,"RebelRelic Vintage Style Guitars"
,"Renaissance Guitars"
,"Reverend Guitars"
,"Richwood Guitars"
,"Rickenbacker"
,"Rickett Customs"
,"Ritter Bass Guitars"
,"RKS Guitars"
,"Rob Allen Guitars"
,"Robin Guitars"
,"Rogue Guitars"
,"Roscoe Guitars"
,"Sadowsky"
,"Samick Guitar"
,"Sandberg Guitars"
,"Schecter Guitars"
,"Sei Bass"
,"Severin Guitarer"
,"Shergold Guitars"
,"Shuker Bass"
,"Simmons Guitars"
,"Simpson-James Guitars"
,"SKC"
,"Skjold Design Guitars"
,"Soller & Sivcak"
,"Spalt Instruments"
,"Spector Basses"
,"Spruce Hill Guitars"
,"Status Graphite"
,"Steinberger"
,"Stellar Guitars"
,"Steward Basses"
,"Stevens Guitars"
,"Sthac Guitars"
,"Stick Enterprises"
,"Suhr Guitars"
,"Sukop Instruments"
,"Surine Basses"
,"Swalwell Guitars"
,"Tacoma Guitars"
,"Takamine"
,"Tanglewood Guitars"
,"Taylor Guitars"
,"Timtone Custom Guitars"
,"Tobias Basses"
,"Tom Martinson Basses"
,"Traben Bass Company"
,"Traveler Guitar"
,"Treker Guitars"
,"Tyler Guitars"
,"U.S. Masters Guitar Works"
,"Wal Basses"
,"Vally Arts Guitars"
,"Warr Guitars"
,"Warrior Instruments"
,"Warwick"
,"Washburn Guitars"
,"Waterstone Guitars"
,"Wechter Guitars"
,"Veillette Guitars"
,"Wendler Electrocoustic"
,"Versoul"
,"Vester Guitars"
,"VIG Guitars"
,"Wild Stringed Instruments"
,"Wilkat Guitars"
,"Wilson Guitar Ventures"
,"Vintage Guitars"
,"Virgier Guitars"
,"Wishbass.com"
,"Wittman Spins"
,"Woodstock"
,"Vox"
,"Xotic"
,"Yamaha"
,"Zachary Guitars"
,"Zemaitis Guitars"
,"Zeta Basses"
,"Zolla Guitars"
,"Zon Guitars"
,"ZZ Ryder Electric Bass & Guitars"
,"Οdyssey bass"
        );

        foreach ($brands as $b) {
            $brand = new Brand();
            $brand->setName($b);
            $brand->setParent('bass');
            $manager->persist($brand);
        }

        $manager->flush();
    }
}