<?php

namespace Jam\CoreBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\FixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Jam\CoreBundle\Entity\Brand;

class LoadBrandsGuitarsData implements FixtureInterface
{
    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $brands = array(
            "Airline"
,"Alembic Inc"
,"Almansa Guitarras"
,"Alvarez Guitars"
,"Amada guitars"
,"Antoria"
,"Aria (guitar company)"
,"Avalon Guitars"
,"AXL Guitars"
,"B.C. Rich"
,"Babicz Guitars"
,"BassLab"
,"Bear Creek Guitars"
,"Beck guitars"
,"Becker guitars"
,"Beltona Resonator Instruments"
,"Beneteau Guitars"
,"Blade Guitars"
,"Bohemian Guitars"
,"Boss Corporation"
,"Brawley Guitars"
,"Breedlove Guitars"
,"Burns London"
,"Burny"
,"C. F. Martin & Company"
,"Campbell American Guitars"
,"Caparison Guitars"
,"Carl Thompson (luthier)"
,"Carr Amplifiers"
,"Carvin Corporation"
,"Československé hudební nástroje"
,"Chapman Guitars"
,"Charvel"
,"Cimar"
,"Cole Clark"
,"Collings Guitars"
,"Conklin Guitars"
,"Cort Guitars"
,"Creston Electric Instrument"
,"Daisy Rock Girl Guitars"
,"Danelectro"
,"DBZ Guitars"
,"Dean Guitars"
,"Del Vecchio (guitar maker)"
,"Dobro"
,"Duesenberg Guitars"
,"Earthwood"
,"Eastwood Guitars"
,"Eko guitars"
,"El Degas guitars"
,"Electrical Guitar Company"
,"Ellis Guitars"
,"Epiphone"
,"ES Guitars"
,"ESP Guitars"
,"Fano Guitars"
,"Fender Custom Shop"
,"Fender Musical Instruments Corporation"
,"Fernandes Guitars"
,"Fibenare Guitars Co."
,"First Act"
,"Flaxwood Guitars"
,"Framus"
,"Freshman Guitars"
,"FujiGen"
,"Furch Guitars"
,"G&L Musical Instruments"
,"Galanti"
,"Garrison Guitars"
,"George Lowden"
,"Giannini"
,"Gibson Guitar Corporation"
,"Godin (guitar manufacturer)"
,"Gordon-Smith Guitars"
,"Greco guitars"
,"Gretsch"
,"Guild Guitar Company"
,"Guitar and Lute Workshop"
,"Guyatone"
,"Hagström"
,"Hallmark Guitars"
,"Hamer Guitars"
,"Harley Benton"
,"Harmony Company"
,"Harvey Thomas"
,"Heartfield"
,"Heritage Guitars"
,"Hondo (guitar company)"
,"Hoshino Gakki"
,"Howe-Orme"
,"Hoyer guitars"
,"Huss & Dalton"
,"Höfner"
,"Ibanez"
,"Infinity Luthiers"
,"Italia Guitars"
,"Jackson Guitars"
,"James Tyler Guitars"
,"Jay Turser"
,"Jean Larrivée"
,"Jerry Jones Guitars"
,"Johnson Guitars"
,"Jolana"
,"Jon Kammerer Guitars"
,"Joseph Lukes Guitars"
,"Kay Musical Instrument Company"
,"Ken Lawrence Instruments"
,"KHS Musical Instruments"
,"Klira"
,"Korg"
,"Kramer Guitars"
,"Kremona"
,"KxK Guitars"
,"Lado Guitars"
,"Lag (company)"
,"Landola"
,"Langcaster Guitars"
,"Larrivée (guitar company)"
,"Lester DeVoe"
,"Levin (guitar company)"
,"Lichty Guitars"
,"Lindert Guitars"
,"Line 6 (company)"
,"List of Peavey guitars"
,"Lotus (guitar)"
,"Luna Guitars"
,"Lyle guitars"
,"Maestro guitars"
,"Market-Rite"
,"Matao guitar"
,"Maton"
,"Matsumoku"
,"Mayones Guitars & Basses"
,"Memphis Guitars"
,"Michael Kelly Guitars"
,"Modulus Guitars"
,"Moniker Guitars"
,"Mosrite"
,"Motor Ave"
,"Music Man (company)"
,"Nashguitars"
,"National Reso-Phonic Guitars"
,"National String Instrument Corporation"
,"Nil guitars"
,"OLP Guitars"
,"Original Musical Instrument Company"
,"Orville by Gibson"
,"Ovation Guitar Company"
,"Parker Guitars"
,"Peavey Electronics"
,"Penco Guitars"
,"Pensa Custom Guitars"
,"Petros Guitars"
,"PRS Guitars"
,"RainSong"
,"Ramírez Guitars"
,"Recording King"
,"Reverend Musical Instruments"
,"Rickenbacker"
,"Ritz Guitars"
,"Robin Guitars"
,"Roland Corporation"
,"Ruokangas Guitars"
,"S. D. Curlee"
,"Sadowsky"
,"Saint Blues Guitar Workshop"
,"Samick"
,"Sandoval Guitars"
,"Santa Cruz Guitar Company"
,"Schecter Guitar Research"
,"Seagull (company)"
,"Shergold"
,"Shergold Marathon"
,"Sho-Bud"
,"Sigma Guitars"
,"Slingerland Drum Company"
,"Smith Custom Amplifiers"
,"Specimen Products"
,"Spector"
,"Squier"
,"Starr Labs"
,"Steinberger"
,"Stella (guitar)"
,"Strunal CZ, a.s."
,"Sugi Guitars"
,"Suhr Guitars"
,"Sundberg Guitars"
,"Supersound Guitars"
,"Tacoma Guitars"
,"Tagima"
,"Takamine Guitars"
,"Tanglewood Guitars"
,"Taylor Guitars"
,"Teisco"
,"Tōkai Gakki"
,"Tom Anderson Guitarworks"
,"Tonante"
,"TYM Guitars"
,"Univox"
,"Valley Arts Guitar"
,"Warmoth guitars"
,"Veleno (guitar)"
,"Vester Guitars"
        );

        foreach ($brands as $b) {
            $brand = new Brand();
            $brand->setName(trim($b));
            $brand->setParent('guitars');
            $manager->persist($brand);
        }

        $manager->flush();
    }
}