<?php

namespace Jam\CoreBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\FixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Jam\CoreBundle\Entity\Brand;

class LoadBrandsKeysData implements FixtureInterface
{
    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $brands = array(
            "Aarhus Pianofabrik"
,"Access Music"
,"Ackerman & Lowe"
,"Ackerman, F.J."
,"Acoustgrand"
,"Acrosonic"
,"Acxel2 by Idarca-Audio Inc (closed)"
,"Adam, F."
,"Adam, G."
,"Adam, M."
,"Adams"
,"Aeolian"
,"Aerts"
,"Ajello"
,"Akai"
,"Albert"
,"Albert & Co."
,"Albion"
,"Albrecht"
,"Alden"
,"Aldrich"
,"Alesis"
,"Alex Steinbach"
,"Alexander"
,"Allgäuer"
,"Allison"
,"Allmendiger"
,"Alois Kern"
,"Altenburg, Frederick"
,"Altenburg, Otto"
,"American Music"
,"American Piano Company (Ampico)"
,"American Pianos"
,"Amherst"
,"Ammer"
,"Amphion"
,"Amyl"
,"Analogic-ACS"
,"Analogue Solutions (Concussor)"
,"Analogue Systems (RS Integrator)"
,"Anderson"
,"Anderson Bros."
,"Anderson Co."
,"Anderson Sons"
,"André"
,"Andreas"
,"Andreys"
,"Angerhöfer"
,"Apollo"
,"Arcade"
,"Archer"
,"Arion Pianofabrik"
,"Arirang"
,"Armstrong"
,"Army & Navy"
,"Arnelli"
,"Arnold"
,"ARP"
,"Artfield"
,"Artmann"
,"Arturia"
,"Asahi"
,"Ashenback"
,"Askolin"
,"Astin-Weight"
,"Astor"
,"Atlas"
,"Auburn"
,"Aucher"
,"August Förster"
,"Auto Piano Co."
,"Babcock, Alpheus"
,"Babcock, Appleton & Babcock"
,"Babcock, Lewis & Alpheus"
,"Bach"
,"Bachman"
,"Bacon, Francis"
,"Bailey"
,"Baldorr & Sons"
,"Baldur"
,"Baldwin"
,"Baltica"
,"Bannerman"
,"Barber London"
,"Barker"
,"Barnes"
,"Barrat & Robinson"
,"Barthol"
,"Bartlett"
,"Bauer"
,"Bauer, J."
,"Baumbach"
,"Baumeister"
,"Baumgardt"
,"Baus"
,"Bay"
,"Beale"
,"Bechner"
,"Bechstein, C."
,"Becker Bros."
,"Becker, J."
,"Behning & Klix"
,"Behning & Sons"
,"Behr Brothers Piano Company"
,"Behringer"
,"Belarus"
,"Belehredek"
,"Bell Piano & Organ Co."
,"Bellak & Sons"
,"Bellman"
,"Bellmont"
,"Benkert"
,"Bennington"
,"Bentley"
,"Berden"
,"Berdux V."
,"Beregszaszy"
,"Berger"
,"Bergmann"
,"Berry"
,"Betting"
,"Beulhoff"
,"Beyer-Rahnefeld"
,"Biber"
,"Biddle"
,"Bieger"
,"Biese, W."
,"Billberg"
,"Birke, Willy"
,"Birnbaum"
,"Bishop"
,"Bjur Bros."
,"Blacet Research"
,"Blasius"
,"Blenheim"
,"Blondel, A."
,"Blondel, G."
,"Blüthner"
,"Boardman, Gray & Co."
,"Bocage"
,"Bock & Hinrichsen"
,"Bogart"
,"Bogs & Voigt"
,"Bohemia"
,"Boisselot & Fils"
,"Bord, A."
,"Borgato"
,"Boston"
,"Boston Piano Co."
,"Boyd"
,"Brackett & Robinson"
,"Brackett, J. W."
,"Bradbury"
,"Bradbury, Wm. B."
,"Bradford"
,"Brambach"
,"Brandtner, H. Rudolf"
,"Branston"
,"Brasil"
,"Brasted"
,"Breitkopf & Härtel"
,"Bremitz"
,"Brentwood"
,"Bretschneider, Alexander"
,"Breyer"
,"Briem"
,"Briggs"
,"Brinkerhoff"
,"Brinkmann"
,"Brinsmead, John"
,"Bristol"
,"Broadway"
,"Broadwood and Sons"
,"Broadwood White"
,"Brodmann"
,"Brooks"
,"Brother"
,"Brown & Allen"
,"Browning"
,"Brunner"
,"Brückner"
,"Brødrene Hals Christiania"
,"Buchla & Associates (200e)"
,"Buchla and Associates"
,"Bulow"
,"Burg van den"
,"Burgasser"
,"Burgdorfer"
,"Burger & Jacobi AG"
,"Burling Mansfield"
,"Bush & Gerts"
,"Bush & Lane"
,"Butler Bros."
,"Byelloruss"
,"Böhme & Sohn"
,"Bösendorfer"
,"Cable Nelson"
,"Cable, Hobart M."
,"Cahn & Cahn"
,"Calisia"
,"Cameo"
,"Cameron"
,"Cappelen"
,"Carlton"
,"Casio"
,"Casio"
,"Cauwenberghe"
,"Chaika"
,"Challen"
,"Challenger"
,"Chappell & Co."
,"Charles Stieff"
,"Chase, A.B."
,"Chassaigne"
,"Chavanne"
,"Cherny"
,"Chickering & Mackays"
,"Chickering and Sons"
,"Chickering Bros."
,"Chickering, Jacob"
,"Chickering, Jonas"
,"Christensen"
,"Christman"
,"Christofori"
,"Chu-Seng"
,"Clark Melville"
,"Classenti"
,"Classic"
,"Clavia"
,"Clement"
,"Clementi"
,"Cline"
,"Club of the Knobs"
,"Club of the knobs"
,"Cockuijt"
,"Collard & Collard"
,"Colonial"
,"Conn"
,"Conover"
,"Continental"
,"Conway"
,"Cornish"
,"Cramer"
,"Crane & Sons, Ltd."
,"Cristofori"
,"Critter and Guitari"
,"Crown"
,"Crumar"
,"Cuijpers, J.F."
,"Cunningham Piano Company"
,"Curetronic"
,"Currier & Co."
,"Currier & Gilbert"
,"Currier Piano Co."
,"Cwejman"
,"Cyndustries (Cynthia)"
,"Czapka"
,"Cäcilia"
,"D.W. Karn"
,"Daesung"
,"Daewoo"
,"Dale Forty"
,"Dalibor"
,"D'almaine"
,"Danemann"
,"Danemann, W"
,"Daniël"
,"Dave Smith Instruments"
,"De Blaise"
,"Debain et Cie"
,"Decker Brothers"
,"Dengler"
,"D'este"
,"Diapason"
,"Diederichs Freres"
,"Dietmann"
,"Disklavier"
,"Dittrich"
,"Dobbert"
,"Dochtermann piano"
,"Doepfer"
,"Doepfer Musikelektronik (A-100)"
,"Does, van der"
,"Doina"
,"Dominion Piano and Organ Co."
,"Donath, Max"
,"Doss, Robert"
,"Doutreligne Piano"
,"Drachman"
,"Dreinhöfer, Wilhelm"
,"Dresden"
,"Dreyer & Co."
,"Driggs & Tooker"
,"Driggs Patent Piano Co."
,"Driggs, Parmelee & Co."
,"Duck-Son & Pinker"
,"Dulcette"
,"Dunham & Sons"
,"Dunham, John B."
,"Dunham, John B. & Co."
,"Duysen"
,"Döhnert"
,"Dörner"
,"Dörr, Carl & Daniel"
,"Eastman"
,"Eavestaff"
,"Ebel & Sohn"
,"Ebel, Carl"
,"Ecke, Carl"
,"Egtved"
,"Ehrbar"
,"Eisenberg"
,"Ekström"
,"Elby (Panther Series)"
,"Elcké"
,"Electro Harmonix (Micro Synthesizer)"
,"Electronic Dream Plant"
,"Electronic Music Studios (EMS)"
,"Elektron"
,"Elias"
,"Elka"
,"Ellington"
,"Elysian"
,"Emerson"
,"Emmer, Wilhelm"
,"E-mu"
,"Ensoniq"
,"Erard & Cie, S.& P."
,"Erard- London"
,"Erbe, J."
,"Ernst Jacob, Mechanik Fabrik Berlin CO"
,"Erste Produktiv-Genossenschaft"
,"Essenfelder"
,"Essex"
,"Estey Piano Corp."
,"Estonia"
,"Eterna"
,"Etyde"
,"Euphona (made by The Cable Company)"
,"Europa"
,"Euterpe"
,"Evans"
,"Everett"
,"Evertides"
,"Fabbrini"
,"Fahr"
,"Fairlight"
,"Falcone"
,"Fandrich & Sons"
,"Fandrich Piano"
,"Farfisa"
,"Farfisa"
,"Farrand"
,"Fayette S. Cable"
,"Fazer Musik"
,"Fazioli"
,"Feigl, Alois"
,"Fenner"
,"Feurich"
,"Fibich"
,"Fibiger"
,"Fiedler, Gustav"
,"Finger"
,"Focké"
,"Forenede"
,"Formanta (Polivoks)"
,"Forrest"
,"Francke"
,"Franz Wolek in Wien"
,"French"
,"French Starck"
,"Fritz Dobbert"
,"Fuchs"
,"Fuchs & Möhr"
,"Fuder, G."
,"Future Retro[1]"
,"Future Sound Systems"
,"Förster & Co."
,"Förster, August"
,"G.Hoffmann"
,"Gaveau"
,"Gebr. Perzina"
,"Geissler, F."
,"Generalmusic"
,"Gerard"
,"Gerbstädt"
,"Gerhard Adams"
,"Gerhard Heintzman"
,"Gerstenberger"
,"Gevaert"
,"Geyer"
,"Giles Pianos Ltd."
,"Gillot-Straube"
,"Glass & Co."
,"Gleeman"
,"Glenz (Josef) Breslau"
,"Glos & Pflug,Wien"
,"Godfrey"
,"Goetze & Co."
,"Goetze-Gross"
,"Gordon & Bailey"
,"Gordon Laughead"
,"Gotha"
,"Gotzmann"
,"Gourlay"
,"Graf, Conrad"
,"Graf, Hermann"
,"Grand"
,"Grande"
,"Gratiae"
,"Grau, F."
,"Grimm"
,"Grinnell Bros."
,"Grotrian"
,"Grotrian-Steinweg"
,"Grover"
,"Grunert"
,"Gulbransen"
,"Gunther & Sohne"
,"Gunther, J."
,"Gustafson & Ljungqvist"
,"Görs & Kallmann"
,"Görs & Spangenberg"
,"Haake, Karl"
,"Haddorff"
,"Haegele of Aalen"
,"Haessler"
,"Hagspiel"
,"Hahn, Alb."
,"Hailun"
,"Hain, Stephan"
,"Haines Bros."
,"Halle & Voight"
,"Hallet, Davis & Co."
,"Hallett & Cumston"
,"Hallett, Russell"
,"Hals"
,"Hamburger"
,"Hamilton"
,"Hammond"
,"Hampton"
,"Hanlet"
,"Hannon Hall"
,"Hansen, A."
,"Hansen, Julius"
,"Hansmann, Gebr."
,"Hardman"
,"Harmsworth & company, Cincinnati"
,"Harrison, V. F."
,"Hartge, Henry"
,"Hartmann Music"
,"Hartmann, W."
,"Harvard"
,"Harwood"
,"Hasche"
,"Hasselaar"
,"Hasseldieck, Dietrich"
,"Hastings"
,"Hauch, J.B."
,"Hausmann"
,"Hautrive"
,"Hayelson"
,"Hayes, E. T."
,"Hayt, Babcock & Appleton"
,"Hayts, Babcock & Appleton"
,"Hazelton & Brother"
,"Hazelton Brothers"
,"Healy"
,"Hedke, Wilh."
,"Hegeler"
,"Heiden, Carl Von"
,"Heinisch"
,"Heintzman & Co."
,"Hellas"
,"Hellström"
,"Helmholz"
,"Heppel & Theilig"
,"Hermann"
,"Herrburger"
,"Herrmann, Alexander"
,"Herz neveu (Philippe)"
,"Herz, Henri"
,"Heyl, Gustav"
,"Hillgärtner, Heinrich"
,"Hindsberg"
,"Hinze"
,"Hlucháň"
,"Hobart M. Cable"
,"Hoek"
,"Hoepfner"
,"Hoerr, Franz"
,"Hoff & Co."
,"Hoffmann & Kühne"
,"Hoffmann, August"
,"Hoffmann, Georg"
,"Hoffmann, W."
,"Hofmann"
,"Hofmann & Czerny"
,"Hofmann & Scholz"
,"Hofmann, Karl"
,"Hohner"
,"Holzl & Heitzmann"
,"Hopkinson"
,"Hornung & Moeller"
,"Howard"
,"Howard Piano Co."
,"Hummel"
,"Humphrey, London"
,"Hundt & Sohn"
,"Huntington"
,"Hupfeld"
,"Hupfer Pianos"
,"Hyfte, van C."
,"HyperSynth"
,"Hyundai"
,"Hölling & Spangenberg"
,"Hörügel"
,"Ibbsynth"
,"J&C Fischer"
,"J. Erbe Eisenach"
,"Jacob Bros."
,"Jahn"
,"James & Holmstrom"
,"Janowsky, M."
,"Janssen"
,"Jarret & Goudge"
,"Jaschinsky, A."
,"Jasper"
,"Jayel"
,"Jefferson"
,"Jehle"
,"Jelmini"
,"Jewett, Boston"
,"John Bowen"
,"John Raper co. Ottawa, Ontario"
,"Jong de"
,"Jurkat, C."
,"Jørgensen, Brødr."
,"Kadenza"
,"Kadette"
,"Kaim"
,"Kaim & Gunther"
,"Kaiser"
,"Kann, Georg"
,"Kappler"
,"Kaps, Ernst"
,"Kasselman"
,"Katzmarek & Co."
,"Kawai"
,"Kawai Musical Instruments"
,"Keislair"
,"Kemble"
,"Kenny & Sons"
,"Kent & Cooper"
,"Kessels"
,"Ketron"
,"Keylard"
,"Kilbourne"
,"Kimball"
,"Kingsburg"
,"Kingsbury (made by The Cable Company)"
,"Kirkman"
,"Kirschner"
,"Kisting"
,"Klavins"
,"Klein"
,"Klima"
,"Klingmann"
,"Kloppe, H."
,"Knabe & Gaehle"
,"Knabe Bros."
,"Knabe, Gaehle & Co."
,"Knabe, Wm. & Co."
,"Knake"
,"Knauer"
,"Knauss"
,"Knight"
,"Knudsen & Sons"
,"Knudsen, J."
,"Knöchel Ad."
,"Koch & Co."
,"Koch & Korselt"
,"Kohler & Campbell"
,"Korg"
,"Kort de"
,"Kraft, Aug."
,"Krakauer"
,"Kranich & Bach"
,"Krause, Max"
,"Krauss"
,"Krell"
,"Krell & French"
,"Kreuizbach"
,"Kreutzbach, Julius"
,"Kreutzer"
,"Kriebel"
,"Kriegelstein"
,"Kriegelstein & Arnaud"
,"Kriegelstein & Plantade"
,"Krumm"
,"Kuhla"
,"Kuhse"
,"Kunst"
,"Kunz"
,"Kupers"
,"Kurtzmann & Sons"
,"Kurzweil Music Systems"
,"La Petite"
,"Labrousse"
,"Lager"
,"Lagonda"
,"Lambert"
,"Lancaster"
,"Lauberger & Gloss"
,"Laughead, Gordon"
,"Laurence & Nash"
,"Laurence & Sons, Alex"
,"Legnica"
,"Leguerinais"
,"Lehman"
,"Lehmann de Lehnsfeld"
,"Lehmann, Adolf"
,"Leichel"
,"Leijser"
,"Lennar Digital"
,"Lerpée, Carl"
,"Lesage"
,"Lester"
,"Leswein"
,"Leutke"
,"Lichtenthal, Hermann"
,"Liederstrom"
,"Liehr"
,"Lieshout & Zonen, M. van"
,"Lighte & Bradburys"
,"Lighte & Ernst"
,"Lighte & Newton"
,"Lighte, F. C."
,"Lighte, Newton & Bradburys"
,"Lincoln"
,"Lindbergh"
,"Lindeman & Sons"
,"Lindeman, Wm."
,"Linden"
,"Lindholm"
,"Lindner"
,"Lindner & Sohn, I.P."
,"Lindsay"
,"Linke"
,"Linn Electronics, Inc."
,"Lipczinsky, Max"
,"Lipp"
,"Lirika"
,"Littmann"
,"Livewire"
,"Livingstone"
,"Lohmann Piano Co."
,"Lorenz"
,"Love, Malcolm"
,"Lowrey"
,"Ludwig"
,"Luis Verdugo & Hijo"
,"Lummer, Wilh."
,"Luner"
,"Lyon & Healy"
,"Lyra"
,"Lyrica"
,"Macbeth Studio Systems"
,"Maeari-Hyundai"
,"Maetzke"
,"Mag"
,"Mage"
,"Magrini"
,"Mahler"
,"Maier,K."
,"Malmsjö"
,"Mand"
,"Mann, Theodor"
,"Manner & Co."
,"Manner & Gabler"
,"Mannhorg"
,"Mansfield"
,"Manthey"
,"Marion"
,"Maristany"
,"Markx"
,"Marschall & Mittauer"
,"Marshall & Rose"
,"Marshall & Wendell"
,"Martins & Ouvrier"
,"Mason & Hamlin"
,"Mason & Risch"
,"Mathuschek, F."
,"Mathushek & Kinkeldey"
,"Mathushek & Kühner"
,"Mathushek & Son"
,"Mathushek Piano Mfg. Co."
,"Matthaes"
,"Mattson Mini Modular"
,"Matz & Co."
,"M-Audio (formerly Midiman)"
,"May"
,"McPhail, A. M."
,"Mecklenburg"
,"Meister"
,"Meldorf"
,"Melford"
,"Melodic"
,"Melville Clark"
,"Menzel"
,"Mercedes"
,"Merkur"
,"Mes, A."
,"Metalbox"
,"Metasonix"
,"Metropolitan"
,"Meyer, Conrad"
,"MFB"
,"Michelle"
,"Mignon"
,"Mikula, Gebr."
,"Miller, Henry F. Miller (Boston)"
,"Minse"
,"Modcan"
,"Monington & Weston"
,"Moog Music"
,"Moore & Moore"
,"Morley, Robert"
,"Morrison & Harrison"
,"Mozart piano company"
,"Mussard"
,"Muzelle"
,"Mühlbach, F."
,"Müller"
,"Müller-Schiedmayer"
,"Mätzke, Ed."
,"Mörs"
,"Nagel"
,"Nakamichi"
,"Native Instruments"
,"Natori"
,"Nelson"
,"Nemetschke"
,"Neuburger, Adolf"
,"Neugebauer"
,"Neumann"
,"Neumeyer, Gebr."
,"Neupert"
,"New England Digital (NED)"
,"New Winsor"
,"Niederländer"
,"Niedermeyer"
,"Nieër"
,"Niemeyer"
,"Niendorf"
,"Nijmatten"
,"Noeske"
,"Nord Piano"
,"Nordiska"
,"Novation"
,"Nützmann, Adolf"
,"Oakley Sound Systems"
,"Oberheim"
,"Otto Bach"
,"PAiA Electronics"
,"PAiA Electronics"
,"Painter & Ewing"
,"Palatino"
,"Paling minor"
,"Pallik & Schicker"
,"Pallik & Stiasny"
,"Palm Products GmbH (PPG)"
,"Pape fils (Frédéric-Eugène)"
,"Pape, Jean-Henri"
,"Pappenberger"
,"Papps"
,"Parttart, Alois"
,"Paukert"
,"Pawlek, Josef"
,"Pearl River"
,"Peek and Son"
,"Pepper"
,"Period Piano Company"
,"Perzina, Gebr."
,"Peterborgh"
,"Petrof"
,"Petrov"
,"Petzold"
,"Peukert"
,"Pfaffe, Julius"
,"Pfeiffer"
,"Pfeiffer, J."
,"Philipps"
,"Phillip"
,"Phillips"
,"Piano Disc"
,"Picassi"
,"Pittsburg Modulars"
,"Plan B"
,"Pleyel"
,"Plymouth"
,"Poestkoke"
,"Pohlmann, Leonhard"
,"Pokorny"
,"Poletti & Tuinman"
,"Pons Gary"
,"Poole"
,"Pramberger"
,"Prein, Friedrich"
,"President"
,"Price & Teeple"
,"Probst, Georg"
,"Produktiv-G.,E."
,"Proksch, A."
,"Proskowec"
,"Protze"
,"Psalmist"
,"Purcell"
,"QuandtQuispel"
,"Quasimidi"
,"Rachals"
,"Raehse-Repia"
,"Rameau"
,"Ramsberger"
,"Rathke, R."
,"Ravenstein"
,"Realtime Music Solutions (RMS)"
,"Red October"
,"reFX"
,"Regent"
,"Reichelt & Birnbaum"
,"Reid Sohn"
,"Reinhard"
,"Reinhold"
,"Reisbach"
,"Rekewitz, Wilh."
,"Renn"
,"Repia"
,"Richard Lipp & Sohn"
,"Ridgewood"
,"Rieger-Kloss"
,"Riese"
,"Riga"
,"Rijken"
,"Rijken & de Lange"
,"Rippen"
,"Ritmüller"
,"Ritter"
,"Robinson"
,"Rogers"
,"Rogers, George"
,"Rohlfing"
,"Rohr, Alfred"
,"Roland"
,"Roland Corporation"
,"Roller & Blanchet"
,"Roloff, H"
,"Ronaldi"
,"Rordorf"
,"Rosenbach"
,"Rosenberg"
,"Rosenkranz"
,"Roth & Junius"
,"Roth Pianos"
,"Royale"
,"Royale-Classic"
,"Rubenstein"
,"Ruch"
,"Rud Ibach Sohn"
,"Russell and Russell"
,"Russell, George"
,"Ruyter"
,"Römhildt"
,"Rönisch"
,"Rösch-Le Sage"
,"Rösler"
,"Rösler, G."
,"Sabel"
,"Sagenhaft"
,"Sakura"
,"Samaniego"
,"Sames,William"
,"Samick"
,"Sandbergen"
,"Sassmann"
,"Saturn"
,"Sauter"
,"Schaaf & Co."
,"Schaaf, Hermann"
,"Schadhauser, Johann"
,"Schafer & Sons"
,"Scharf & Hauk"
,"Scheel, Carl"
,"Schell, Lothar"
,"Schellenkens, G."
,"Schemelli & Co."
,"Schiedmayer & Soehne"
,"Schiedmayer, J.& P."
,"Schiller"
,"Schilling, Fr."
,"Schimmel"
,"Schindhelm"
,"Schindler"
,"Schirmer & Son"
,"Schlögl"
,"Schmidt"
,"Schmidt Pianos"
,"Schmidt-Flohr"
,"Schmitz"
,"Schnell, R.A."
,"Scholze"
,"Schroeder"
,"Schröder, C.M."
,"Schröther"
,"Schubert"
,"Schuerman"
,"Schuetze & Ludolff"
,"Schultz & Sons"
,"Schulze & Pollmann"
,"Schulze & Sohn"
,"Schumann"
,"Schuppe & Neumann"
,"Schwechten, G."
,"Schweighofer"
,"Schwester"
,"Schütz & Co."
,"Schütze"
,"Seeger"
,"Seidel, Rob."
,"Seidl & Sohn"
,"Seiler, Ed."
,"Seiler, Max"
,"Sejung Piano Co."
,"Sequential Circuits"
,"Settergren"
,"Settergren Piano Co."
,"Seuffert"
,"Sherlock - Manning"
,"Sherman, Clay"
,"Shigeru"
,"Shigeru Kawai"
,"Shima-Jehle"
,"Shimler"
,"Shoninger"
,"Shorewood"
,"Siegel, Rudolf[1]"
,"Siel"
,"Siewert"
,"Silbermann"
,"Singer"
,"Skop"
,"Smart, Charles"
,"Snel"
,"Sohmer & Co."
,"Sojin"
,"Solton"
,"Sonor"
,"Sonore"
,"Soph, Joseph"
,"Sopnnagel"
,"Sound Transform Systems"
,"Soward"
,"Spaethe Wilh."
,"Spectrasonics"
,"Spencer"
,"Spencer & Murdoch"
,"Squire"
,"Squire and Longson"
,"Standaart"
,"Stapel"
,"Starck"
,"Starckette & Kenmore"
,"Starr Piano Co."
,"Staub & Co."
,"Staub, J."
,"Steck"
,"Steck, George"
,"Steger & Sons"
,"Steigerman"
,"Stein"
,"Steinbach"
,"Steinbach, Alex"
,"Steinberg"
,"Steinberg, Gerh."
,"Steinberg, Wilh"
,"Steiner, B."
,"Steiner, Bernhard"
,"Steiner-Parker"
,"Steingraeber & Söhne"
,"Steinhoven"
,"Steinmann, Wilh."
,"Steinmayer"
,"Steinthal, L."
,"Steinway & Sons"
,"Steinway Haus"
,"Stelzhammer"
,"Stenger"
,"Sterling"
,"Stichel, F."
,"Stingl, Gebr."
,"Stingl, Ignaz"
,"Stockholm"
,"Stoddart"
,"Story & Clark"
,"Straub"
,"Strauss"
,"Streicher"
,"Strindberg"
,"Strohmenger & Sons"
,"Strothier"
,"Stroud"
,"Stuart and Sons"
,"Studio Electronics"
,"Stultz"
,"Sturn"
,"Stöcker, Theodor"
,"Suzuki"
,"Svahnquist"
,"Svenska"
,"Synthesis Technology (MOTM)"
,"Synthesizers.com"
,"Synthesizers.com"
,"Synthetic Music Systems"
,"Synthetic Sound Labs"
,"Sängler & Sohne"
,"Tallone"
,"Tamta"
,"Taubert"
,"Tchaikovsky"
,"Technics"
,"Technosaurus"
,"Teisco"
,"Temple"
,"Tetsch & May"
,"Thalèn"
,"Thayer"
,"The Cable Company"
,"The Harvestman"
,"Theilig, Rich."
,"Thein"
,"Therson"
,"Thomas & Avarsea"
,"Thuringer"
,"Thürmer, Ferd."
,"Tiptop Audio"
,"Tokiwa"
,"Tolkien"
,"tonk"
,"Tormin, C."
,"Toyo"
,"Toyo Appolo"
,"Trautwein"
,"Trübger, Emil"
,"Tschaika"
,"Tuch & Geyer"
,"Uebel & Lechleiter"
,"Ukraina"
,"United Piano Makers, New York"
,"Urbas & Kuhne"
,"Urbas & Reishauer"
,"Urbas, Johann"
,"Urk & Sons"
,"W. P. Emerson Piano Co."
,"Waddington"
,"Wagner"
,"Waldhäusl, Robert"
,"Waldorf Music"
,"Waldstein"
,"Wallace Ash"
,"Wallace Pianoforte Co."
,"Walsmann M."
,"Walter, Charles R."
,"Waltham Piano Co."
,"Van Broad"
,"Van der Does"
,"Van Hyfte"
,"Van Lieshout"
,"Van Veen J."
,"Van Veen W."
,"Van Vloten"
,"Warfield"
,"Wasniczek"
,"Waters, Horace"
,"Watlen, John"
,"Weaver"
,"Weber"
,"Webster"
,"Wegman"
,"Wegman Pianos"
,"Weidenslaufer"
,"Weidig, C."
,"Weihenmeyer & Co."
,"Weinbach"
,"Weinstein and Sons"
,"Weiss"
,"Weissbrod"
,"Wellington (made by The Cable Company)"
,"Welmar"
,"Welzel P.F."
,"Wendl & Lung"
,"Werch, Lothar"
,"Verkooij"
,"Vermy"
,"Werner, F.W."
,"Werner, Hans"
,"Wertheim"
,"Vertigrand"
,"Westbrook"
,"Westerlund"
,"Westermeyer"
,"Wetzel"
,"Whelpdale"
,"Whitmore"
,"Whitney"
,"Whittaker"
,"Wiard Synthesizer Company"
,"Victor W.H Paling & Co"
,"Wieck"
,"Wieler"
,"Vijgeboom Joh."
,"Vijgeboom Johs."
,"Wilhelm Spaethe Gera."
,"Wilkinson & Wornum"
,"Wilkinson, George"
,"Willermann"
,"William Wallace Kimball"
,"Williams & Son, R.S."
,"Williams Piano Co."
,"Williamson"
,"Willis & Co."
,"Wilson"
,"Winchester"
,"Windhofer, Rudolf"
,"Windover (London)"
,"Windsor"
,"Winkelmann & Co."
,"Winkler, Paul"
,"Winter & Co."
,"Wittmayer"
,"Witton and Witton"
,"Vogel & Co."
,"Vogel & Sohn"
,"Vogel, Robert"
,"Vogeler & Co."
,"Wohlfahrt"
,"Voigt, Adolf Ernst"
,"Wolfframm"
,"Volkening"
,"Vollmer"
,"Woodchester"
,"Wornum, Robert"
,"Wornum, Robt. & Sons"
,"Vose & Sons"
,"Vough"
,"Wurlitzer"
,"Wyman"
,"Xinghai Beijing Piano Co."
,"Yamaha"
,"Yamaha"
,"Ühlmann"
,"Young Chang"
,"Zadok Audio & Media Products' SAM-1"
,"Zahl, Georg"
,"Zeitter & Winkelmann"
,"Zender, Sydney"
,"Zimmermann"
,"Zwang"
,"Zwicki"
        );

        foreach ($brands as $b) {
            $brand = new Brand();
            $brand->setName(trim($b));
            $brand->setParent('keys');
            $manager->persist($brand);
        }

        $manager->flush();
    }
}