<?php

namespace Jam\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function isEmailUnique($email)
    {

        $qb = $this->getEntityManager()->createQueryBuilder('u');
        $qb->select('u')
            ->from('JamUserBundle:User', 'u')
            ->where('u.email = :email')
            ->setParameter('email', $email);

        $query = $qb->getQuery();
        $result = $query->getResult();

        return (count($result) > 0) ? false : true;

    }
}
